### ISSUE TITLE
Merge https://github.com/giuseppe998e/simple-cache-rs into this app

### ISSUE THREAD

**Issue by calvinbrown085** [calvinbrown085/simple-cache-rs#2]
@giuseppe998e Would you mind merging your changes into this? I like what you did!

**Comment by giuseppe998e** [comment]
Sure! I had opened a pull request, but then canceled it to redo the fork...

**Comment by calvinbrown085** [comment]
No problem!

**Comment by calvinbrown085** [comment]
This is done!
