### ISSUE TITLE
I've made a mistake

### ISSUE THREAD

**Issue by giuseppe998e** [calvinbrown085/simple-cache-rs#4]
I've made a mistake.  
I just found that `HashMaps` already store their `values` in heap memory. (Just like `Vectors`.)  
So please change this lines:

---
https://github.com/calvinbrown085/simple-cache-rs/blob/b0d270c87cbcd9800b447e72c1c8cfcb3cedc3fe/src/lib.rs#L14
```rust
hashmap: HashMap<K, Entry<V>>,
```

---
https://github.com/calvinbrown085/simple-cache-rs/blob/b0d270c87cbcd9800b447e72c1c8cfcb3cedc3fe/src/lib.rs#L37
```rust
hashmap: HashMap::new(),
```

---
Nothing else needs to be changed. :grin:

**Comment by calvinbrown085** [comment]
No worries, fixed in https://github.com/calvinbrown085/simple-cache-rs/commit/2dd31d85e1e5e80da3b73c5425ee7aa85757dd2e
