### ISSUE TITLE
Add method for retrieving all (K, V) pairs.

### ISSUE THREAD

**Issue by calvinbrown085** [calvinbrown085/simple-cache-rs#6]
We have a method for inserting a batch of values. We also allow the caller to get all keys, and all values, we should allow them to get all key value pairs.

**Comment by giuseppe998e** [comment]
One possible solution is
```rust
pub fn tuples(&self) -> Vec<(K, V)> {
  self.hashmap.iter()
              .map(|(k, v)| (k.clone(), v.value.clone()))
              .collect::<Vec<(K, V)>>()
}
```

**Comment by calvinbrown085** [comment]
Added in https://github.com/calvinbrown085/simple-cache-rs/commit/167a8aee6e78efb6c7bed65539e0eee4bdfffbce
